### ISSUE TITLE
Missing .h folders

### ISSUE THREAD

**Issue by miltkall** [PhilippFux/ESP32_CAN_Interface#4]
I think that the following **.h** folders are **missing**. Could you please commit them and push them on github. Thanks!

https://github.com/PhilippFux/ESP32_CAN_Interface/blob/adf0d39e3e7609e804f2fe6fe00998b796990170/CAN_Interface/CAN_Interface.ino#L12-L18

**Comment by miltkall** [comment]
@ebroecker

**Comment by miltkall** [comment]
@PhilippFux

**Comment by ebroecker** [comment]
I'll do - give me some time.

Am Fr., 27. März 2020 um 03:41 Uhr schrieb Kallianis Miltiadis
<notifications@github.com>:

**Comment by ebroecker** [comment]
please have a look to https://github.com/ebroecker/ESP32_CAN_Interface/tree/enable_websockets_and_http

or here: https://github.com/PhilippFux/ESP32_CAN_Interface/pull/3

**Comment by miltkall** [comment]
I will clone and try to compile again the next days, hope this time everything works out. 

Many thanks!
